project:
  type: website
website:
  title: "chariblog"
  site-url: https://cstorm125.github.io
  description: "A collection of technical writings on applied science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/cstorm125
      - icon: linkedin
        href: https://www.linkedin.com/in/cstorm125/
      - icon: google
        href: https://scholar.google.com/citations?user=UX36NGkAAAAJ
format:
  html:
    theme: litera
    css: styles.css
execute:
  freeze: auto


