[project]
name = "cstorm125-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogluon>=1.3.1",
    "seaborn>=0.13.2",
    "ucimlrepo>=0.0.7",
]
